[package]
name = "pdf"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
pulldown-cmark = "0.13"
typst-as-lib = { version = "0.14", features = ["typst-kit-fonts", "typst-kit-embed-fonts"] }
typst-library = "0.13"
typst-pdf = "0.13"
